version: '3.8'
services:
  noteManager:
    build: .
    container_name: note_manager-container
    image: nate_manager_image
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/noteManagerDb

  db:
    image: postgres:14-alpine
    container_name: db-container
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=noteManagerDb
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=test